// Generated by CoffeeScript 1.9.1
(function() {
  var connection, finit, fs, i, len, map, mysql, pCode, pStart, pStop, q, ref, request, sql1, sql2, tStart, tStop, v, versionOf;

  module.exports = new (require('events')).EventEmitter;

  mysql = require('mysql');

  fs = require('fs');

  versionOf = fs.statSync(process.argv[1]).mtime.toISOString().slice(0, 10);

  request = "pCode=2RH31S101XG01&pStart=200910061523&pStop=201103281305";

  if (process.argv.length === 3) {
    if (process.argv[2] !== '') {
      request = process.argv[2];
    }
  }

  map = {};

  ref = request.split('&');
  for (i = 0, len = ref.length; i < len; i++) {
    q = ref[i];
    v = q.split('=');
    map[v[0]] = v[1];
  }

  pCode = map['pCode'];

  pStart = map['pStart'];

  pStop = map['pStop'];

  tStart = pStart.replace(/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})/, "$1-$2-$3 $4:$5");

  tStop = pStop.replace(/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})/, "$1-$2-$3 $4:$5");

  sql1 = "select name, nserv from svod_code where code='" + pCode + "';";

  sql2 = "select tstamp, value, vf, hand, a_ext from dx\nwhere code = '" + pCode + "'\nand tstamp between '" + pStart + "' and '" + pStop + "'\norder by 1 desc;";

  connection = mysql.createConnection({
    host: 'ec2-54-208-78-75.compute-1.amazonaws.com',
    user: 'userairs',
    password: 'userairs',
    database: 'airs'
  });

  finit = function() {
    connection.end('');
    console.log("</ROWSET>");
    return module.exports.emit('</ROWSET>');
  };

  console.log("<?xml version='1.0' encoding='UTF-8'?>\n<ROWSET autor='is10-99' versionOf='" + versionOf + "'>\n<!-- " + process.argv[1] + "\n?" + request + " -->\n<PARAMS pCode='" + map['pCode'] + "' pStart='" + map['pStart'] + "' pStop='" + map['pStop'] + "' />\n<interval pStart='" + tStart + "' pStop='" + tStop + "'/>\n<!-- " + sql1 + "  -->\n<!-- " + sql2 + "  -->");

  connection.connect;

  connection.query(sql1, function(err1, rows1, fields1) {
    if (err1) {
      console.log("<error1> <![CDATA[" + err1 + "]]></error1>");
      return finit('');
    } else {
      if (rows1.length === 0) {
        finit('');
        return;
      }
      return connection.query(sql2, function(err2, rows2, fields2) {
        var fild, j, k, len1, len2, row, val;
        if (err2) {
          console.log("<error2> <![CDATA[" + err2 + "]]></error2>");
          return finit('');
        } else {
          console.log("<signal>\n<name><![CDATA[" + rows1[0]['name'] + "]]></name>\n<nserv><![CDATA[" + rows1[0]['nserv'] + "]]></nserv>\n</signal>");
          for (j = 0, len1 = rows2.length; j < len1; j++) {
            row = rows2[j];
            console.log("<ROW>");
            for (k = 0, len2 = fields2.length; k < len2; k++) {
              fild = fields2[k];
              if (fild.name === 'tstamp') {
                val = row['tstamp'].replace(/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})/, "$1-$2-$3 $4:$5");
              } else {
                val = row[fild.name];
              }
              console.log("<" + fild.name + "><![CDATA[" + val + "]]></" + fild.name + ">");
            }
            console.log("</ROW>");
          }
          return finit('');
        }
      });
    }
  });

}).call(this);
